In [53]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# import seaborn as sns
import pickle
import tensorflow as tf

In [54]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [55]:
df = pd.read_csv('/content/drive/MyDrive/Document from Ayushman Tomar')

In [56]:
df

English  \
0                                                   Help!   
1                                                   Jump.   
2                                                   Jump.   
3                                                   Jump.   
4                                                  Hello!   
...                                                   ...   
130471  Examples of art deco construction can be found...   
130472                          and put it in our cheeks.   
130473  As for the other derivatives of sulphur , the ...   
130474  its complicated functioning is defined thus in...   
130475  They've just won four government contracts to ...   

                                                    Hindi  
0                                                   बचाओ!  
1                                                   उछलो.  
2                                                   कूदो.  
3                                                  छलांग.  
4                                                 नमस्ते।  
...                                                   ...  
130471  आर्ट डेको शैली के निर्माण मैरीन ड्राइव और ओवल ...  
130472                    और अपने गालों में डाल लेते हैं।  
130473  जहां तक गंधक के अन्य उत्पादों का प्रश्न है , द...  
130474  Zरचना-प्रकिया को उसने एक पहेली में यों बांधा है .  
130475  हाल ही में उन्हें सरकारी ठेका मिला है करीब सौ ...  

[130476 rows x 2 columns]

In [57]:
df.isna().sum()

English      2
Hindi      312
dtype: int64

In [58]:
df.dropna(axis=0,inplace=True)

In [59]:
df.isna().sum()

English    0
Hindi      0
dtype: int64

In [60]:
english=df.iloc[:80000,0]
english

0                                                    Help!
1                                                    Jump.
2                                                    Jump.
3                                                    Jump.
4                                                   Hello!
                               ...                        
80189    Perhaps one of the largest complexes in this s...
80190    Muslims believe in only one God, whom they cal...
80191    Remaining scientific uncertainties includes ho...
80192    And then she would simply put her hand out and...
80193    The overhang of the unofficial debt , though ,...
Name: English, Length: 80000, dtype: object

In [61]:
hindi=df.iloc[:80000,-1]
hindi

0                                                    बचाओ!
1                                                    उछलो.
2                                                    कूदो.
3                                                   छलांग.
4                                                  नमस्ते।
                               ...                        
80189    मंदिरों की इस श्रृंखला में शायद सबसे बड़ा परिस...
80190    मुसलमान एक ही ईश्वर को मानते हैं जिसे वो अल्ला...
80191    शेष वैज्ञानिक अनिश्चितताओं (uncertainties) में...
80192                और फिर वो अपना हाथ आगे कर के कहती थी,
80193    हालंकि अनधिकृत कर्ज का मामल अभी भी बदस्तूर जार...
Name: Hindi, Length: 80000, dtype: object

In [62]:
import re
import string
def clean(text):
    text = re.sub(',', ' ', text)
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = re.sub('”', '', text)
    text = re.sub('“', '', text)
    text = re.sub('’', '', text)
    text = re.sub('‘', '', text)
    text = re.sub('\\n', ' ', text)
    text = text.lower()
    text = re.sub(' +', ' ', text)
    return text

In [63]:
english = english.apply(clean)
english

0                                                     help
1                                                     jump
2                                                     jump
3                                                     jump
4                                                    hello
                               ...                        
80189    perhaps one of the largest complexes in this s...
80190    muslims believe in only one god whom they call...
80191    remaining scientific uncertainties includes ho...
80192    and then she would simply put her hand out and...
80193    the overhang of the unofficial debt though per...
Name: English, Length: 80000, dtype: object

In [64]:
import unicodedata
def get_hindi_punctuations():
    hindi_punctuations = []
    for i in range(0x2000, 0x206f + 1):
        char = chr(i)
        if unicodedata.category(char) == 'Po':
            hindi_punctuations.append(char)
    return hindi_punctuations

hindi_punctuation = get_hindi_punctuations()

In [65]:
def clean_hindi(text):
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = re.sub('[a-zA-Z0-9]', '',text)
    text = re.sub('।', '',text)
    text = re.sub(' +', ' ', text)
    return ''.join(c for c in text if c not in hindi_punctuation)


hindi = hindi.apply(clean_hindi)

In [66]:
hindi[10000]

'अब हो सकता है हम वो ना माने जो धर्म हमें सिखाने की कोशिश कर रहे हैं'

In [67]:
english[10000]

'now we may not agree with what religions are trying to teach us '

In [68]:
hindi = hindi.values
hindi

array(['बचाओ', 'उछलो', 'कूदो', ...,
       'शेष वैज्ञानिक अनिश्चितताओं में भविष्य का गर्म तापमान और पूरे विश्व के अलगअलग भागों में गर्मी और संबंधित परिवर्तनों की भिन्नता शामिल हैज्यादातर राष्ट्रीय सरकारों ने क्योटो प्रोटोकॉल पर हस्ताक्षर कर दिए हैं और उसकी तस्दीक़ भी कर दी है क्योटो प्रोटोकॉल का उद्देश्य ग्रीनहाउस गैसों ओ कम करना है पर सारे संसार में राजनितिक और लोक बहस छिडी हुई है की कोई कदम उठाना चाहिए के नही ताकि भविष्य में वार्मिंग को कम किया जा सके या उलटाया जा सके या उसके असर को ढाला जा सके',
       'और फिर वो अपना हाथ आगे कर के कहती थी',
       'हालंकि अनधिकृत कर्ज का मामल अभी भी बदस्तूर जारी है '],
      dtype=object)

In [69]:
english = english.values
english

array(['help', 'jump', 'jump', ...,
       'remaining scientific uncertainties includes hot temperature in future and heat in different regions of the world and difference in the related changes most national governments have signed kyoto protocol and has been given acceptance the purpose of kyoto protocol is to reduce the greenhouse gases but in the whole world political and public debate is on if any step should be taken or not so that in future warming can be reduced or reversed or its effect can be adapted',
       'and then she would simply put her hand out and say ',
       'the overhang of the unofficial debt though persists '],
      dtype=object)

In [70]:
hindi_merged=[]

for lst in hindi:
    sentence="sos "
    for word in lst.split(" "):
        sentence=sentence+word+" "
    hindi_merged.append(sentence.strip()+" eos")

In [71]:
hindi_merged[1223]

'sos तुम हमेशा शिकायत करते रहते हो eos'

In [72]:
english[1223]

'you are always complaining'

In [73]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [74]:
tokenizer_eng = Tokenizer()

In [75]:
tokenizer_eng.fit_on_texts(english)

In [76]:
tokenizer_eng.word_index

{'the': 1,
 'of': 2,
 'and': 3,
 'to': 4,
 'in': 5,
 'a': 6,
 'is': 7,
 'that': 8,
 'was': 9,
 'it': 10,
 'for': 11,
 'this': 12,
 'on': 13,
 'are': 14,
 'as': 15,
 'with': 16,
 'by': 17,
 'he': 18,
 'be': 19,
 'you': 20,
 'not': 21,
 'his': 22,
 'or': 23,
 'from': 24,
 'which': 25,
 'have': 26,
 'but': 27,
 'i': 28,
 'at': 29,
 'has': 30,
 'they': 31,
 'we': 32,
 'were': 33,
 'an': 34,
 'there': 35,
 'its': 36,
 'one': 37,
 'can': 38,
 'all': 39,
 'their': 40,
 'india': 41,
 'had': 42,
 'so': 43,
 'also': 44,
 'if': 45,
 's': 46,
 'these': 47,
 'when': 48,
 'who': 49,
 'other': 50,
 'will': 51,
 'about': 52,
 'people': 53,
 'them': 54,
 'more': 55,
 'been': 56,
 'what': 57,
 'rrb': 58,
 'time': 59,
 'lrb': 60,
 'like': 61,
 'after': 62,
 'some': 63,
 'only': 64,
 'do': 65,
 'no': 66,
 'out': 67,
 'indian': 68,
 'any': 69,
 'two': 70,
 'up': 71,
 'many': 72,
 'him': 73,
 'government': 74,
 'your': 75,
 'very': 76,
 'first': 77,
 'world': 78,
 'into': 79,
 'her': 80,
 'because': 81,
 'y

In [77]:
tokenizer_hindi = Tokenizer()

In [78]:
tokenizer_hindi.fit_on_texts(hindi_merged)

In [79]:
tokenizer_hindi.word_index

{'sos': 1,
 'eos': 2,
 'के': 3,
 'है': 4,
 'में': 5,
 'की': 6,
 'और': 7,
 'से': 8,
 'का': 9,
 'को': 10,
 'हैं': 11,
 'एक': 12,
 'पर': 13,
 'कि': 14,
 'भी': 15,
 'यह': 16,
 'नहीं': 17,
 'लिए': 18,
 'इस': 19,
 'था': 20,
 'ने': 21,
 'ही': 22,
 'कर': 23,
 'जो': 24,
 'हो': 25,
 'किया': 26,
 'तो': 27,
 'करने': 28,
 'या': 29,
 'गया': 30,
 'अपने': 31,
 'तथा': 32,
 'थे': 33,
 'कुछ': 34,
 'वह': 35,
 'तक': 36,
 'थी': 37,
 'आप': 38,
 'वे': 39,
 'साथ': 40,
 'जाता': 41,
 'रूप': 42,
 'दिया': 43,
 'भारत': 44,
 'होता': 45,
 'हम': 46,
 'द्वारा': 47,
 'बहुत': 48,
 'ये': 49,
 'बाद': 50,
 'किसी': 51,
 'कोई': 52,
 'सकता': 53,
 'मैं': 54,
 'जब': 55,
 'करते': 56,
 'समय': 57,
 'जा': 58,
 'अपनी': 59,
 'रहे': 60,
 'लेकिन': 61,
 'उनके': 62,
 'तरह': 63,
 'हुआ': 64,
 'सकते': 65,
 'होने': 66,
 'न': 67,
 'उस': 68,
 'अधिक': 69,
 'होती': 70,
 'रहा': 71,
 'हुए': 72,
 'उन्हें': 73,
 'करना': 74,
 'वाले': 75,
 'पहले': 76,
 'इसके': 77,
 'इन': 78,
 'उसे': 79,
 'उसके': 80,
 'क्या': 81,
 'काम': 82,
 'बात': 83,
 'उन्होंने': 84,

In [80]:
word_count_hindi =len(tokenizer_hindi.word_index)
word_count_hindi

61210

In [81]:
word_count_eng =len(tokenizer_eng.word_index)
word_count_eng

55965

In [82]:
eng_seq=tokenizer_eng.texts_to_sequences(english)
eng_seq

[[157],
 [4992],
 [4992],
 [4992],
 [8572],
 [8572],
 [16282],
 [16282],
 [174, 10],
 [260, 3568],
 [6111],
 [153, 5],
 [103, 67],
 [138, 267],
 [12230],
 [1968],
 [1968],
 [2590],
 [2590],
 [26, 2313],
 [26, 2313],
 [26, 2313],
 [28, 6404],
 [28, 6404],
 [865, 741],
 [260, 1233],
 [260, 381],
 [1072, 138],
 [1089, 121],
 [1553, 1764],
 [4540, 121],
 [5599],
 [28, 1013, 43],
 [28, 8046],
 [260, 6405],
 [260, 2421],
 [260, 2992],
 [36, 1461],
 [49, 1589],
 [49, 1589],
 [49, 1589],
 [49, 1589],
 [2682],
 [1553, 3737],
 [153, 13, 5],
 [4541],
 [229, 717],
 [914, 10941],
 [952, 73],
 [28, 479, 2992],
 [28, 38, 5850],
 [28, 38, 5850],
 [28, 299, 20],
 [28, 299, 20],
 [28, 299, 20],
 [28, 299, 20],
 [28, 299, 20],
 [28, 51, 607],
 [260, 656],
 [260, 4542],
 [260, 4542],
 [551, 73, 5],
 [551, 73, 5],
 [551, 121, 67],
 [337, 240],
 [979, 1783],
 [1047, 97],
 [1047, 97],
 [3192, 8],
 [229, 5851],
 [229, 5851],
 [18, 2263, 71],
 [1639, 793],
 [107, 14, 20],
 [107, 14, 20],
 [107, 14, 20],
 [107,

In [83]:
hindi_seq=tokenizer_hindi.texts_to_sequences(hindi_merged)
hindi_seq

[[1, 32768, 2],
 [1, 32769, 2],
 [1, 24381, 2],
 [1, 13566, 2],
 [1, 13567, 2],
 [1, 9222, 2],
 [1, 24382, 2],
 [1, 32770, 2],
 [1, 2796, 14, 17, 2],
 [1, 54, 348, 140, 2],
 [1, 48, 3442, 2],
 [1, 781, 167, 2845, 2],
 [1, 234, 1000, 2845, 2],
 [1, 872, 2845, 2],
 [1, 15516, 32771, 2],
 [1, 1953, 2],
 [1, 350, 2],
 [1, 873, 1607, 4, 2],
 [1, 32772, 2],
 [1, 10043, 74, 2],
 [1, 18900, 74, 2],
 [1, 10043, 1741, 2],
 [1, 54, 2003, 30, 2],
 [1, 54, 2003, 112, 2],
 [1, 54, 944, 6740, 2],
 [1, 54, 348, 140, 2],
 [1, 420, 1882, 334, 30, 4, 2],
 [1, 2939, 6741, 2],
 [1, 108, 849, 86, 2],
 [1, 12101, 5893, 11, 2],
 [1, 5429, 1761, 2],
 [1, 48, 32773, 2],
 [1, 10943, 6, 83, 4, 61, 2342, 22, 4, 2],
 [1, 54, 32774, 2],
 [1, 54, 10944, 25, 71, 140, 2],
 [1, 420, 32775, 25, 722, 4, 2],
 [1, 54, 4192, 30, 140, 2],
 [1, 5894, 25, 116, 4, 2],
 [1, 817, 109, 2],
 [1, 15517, 196, 4, 2],
 [1, 4573, 196, 4, 2],
 [1, 4573, 1779, 4, 2],
 [1, 2621, 2],
 [1, 12101, 6437, 11, 2],
 [1, 781, 167, 2845, 2],
 [1, 64

In [84]:
for key, value in tokenizer_eng.word_index.items():
    if value == 14814:
        print(f"The key for value 31723 is '{key}'")
        break

The key for value 31723 is 'dhanushkodi'


In [85]:
## Saving tokened class for prediction
with open('eng_tokenizer.pkl', 'wb') as f:
    pickle.dump(tokenizer_eng, f)

with open('hindi_tokenizer.pkl', 'wb') as f:
    pickle.dump(tokenizer_hindi, f)

In [86]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [87]:
max_len_english = max([len(x) for x in eng_seq])
max_len_hindi = max([len(x) for x in hindi_seq])

In [88]:
max_len_english,max_len_hindi

(349, 314)

In [89]:
padded_input_sequences = pad_sequences(eng_seq, maxlen = max_len_english, padding='post')
padded_output_sequences = pad_sequences(hindi_seq, maxlen = max_len_hindi, padding='post')

In [90]:
padded_input_sequences

array([[  157,     0,     0, ...,     0,     0,     0],
       [ 4992,     0,     0, ...,     0,     0,     0],
       [ 4992,     0,     0, ...,     0,     0,     0],
       ...,
       [ 2507,   833, 12353, ...,     0,     0,     0],
       [    3,    87,    96, ...,     0,     0,     0],
       [    1, 55965,     2, ...,     0,     0,     0]], dtype=int32)

In [91]:
padded_output_sequences

array([[    1, 32768,     2, ...,     0,     0,     0],
       [    1, 32769,     2, ...,     0,     0,     0],
       [    1, 24381,     2, ...,     0,     0,     0],
       ...,
       [    1,  1246,   673, ...,     0,     0,     0],
       [    1,     7,   106, ...,     0,     0,     0],
       [    1,  2851, 11189, ...,     0,     0,     0]], dtype=int32)

In [92]:
padded_output_sequences.shape,padded_input_sequences.shape

((80000, 314), (80000, 349))

In [93]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(padded_input_sequences, padded_output_sequences, test_size=0.1, random_state=0)

In [94]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((72000, 349), (8000, 349), (72000, 314), (8000, 314))

# Model build

In [95]:
from tensorflow.keras.layers import LSTM, Dropout, Dense, Embedding, Bidirectional, Add, Concatenate, Dropout
from tensorflow.keras import Input, Model

In [96]:
max_len_english,max_len_hindi

(349, 314)

In [97]:
word_count_eng+=1
word_count_hindi+=1
word_count_eng,word_count_hindi

(55966, 61211)

In [98]:
# import tensorflow as tf
# # Check TPU availability and initialize the TPU
# try:
#     tpu = tf.distribute.cluster_resolver.TPUClusterResolver()  # TPU detection
#     tf.config.experimental_connect_to_cluster(tpu)
#     tf.tpu.experimental.initialize_tpu_system(tpu)
#     strategy = tf.distribute.TPUStrategy(tpu)
#     print("Running on TPU")
# except ValueError:
#     strategy = tf.distribute.get_strategy()  # Default strategy that works on CPU and single GPU
#     print("Running on CPU or single GPU")

In [99]:
with strategy.scope():
  # Encoder
  encoder_input = Input(shape=(None, ))
  encoder_embd = Embedding(word_count_eng,100, mask_zero=True)(encoder_input)
  encoder_lstm = Bidirectional(LSTM(256, return_state=True))
  encoder_output, forw_state_h, forw_state_c, back_state_h, back_state_c = encoder_lstm(encoder_embd)
  state_h_final = Concatenate()([forw_state_h, back_state_h])
  state_c_final = Concatenate()([forw_state_c, back_state_c])

  # takeing only states and create context vector
  encoder_states= [state_h_final, state_c_final]

  # Decoder
  decoder_input = Input(shape=(None,))
  # For zero padding we have added +1 in hindi vocab size
  decoder_embd = Embedding(word_count_hindi, 100, mask_zero=True)
  decoder_embedding= decoder_embd(decoder_input)
  # We used bidirectional layer above so we have to double units of this lstm
  decoder_lstm = LSTM(512, return_state=True,return_sequences=True )
  # Only output of this decoder dont need self states
  decoder_outputs, _, _= decoder_lstm(decoder_embedding, initial_state=encoder_states)

  # convert predicted numbers into probability using softmax
  decoder_dense= Dense(word_count_hindi, activation='softmax')
  # again feed predicted output into decoder to predict its next word
  decoder_outputs = decoder_dense(decoder_outputs)

  model5 = Model([encoder_input, decoder_input], decoder_outputs)
  model5.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [100]:
model5.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_3 (InputLayer)        [(None, None)]               0         []                            
                                                                                                  
 embedding_2 (Embedding)     (None, None, 100)            5596600   ['input_3[0][0]']             
                                                                                                  
 input_4 (InputLayer)        [(None, None)]               0         []                            
                                                                                                  
 bidirectional_1 (Bidirecti  [(None, 512),                731136    ['embedding_2[0][0]']         
 onal)                        (None, 256),                                                  

In [101]:
EPOCHS = 25

In [102]:

from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping

In [103]:
# Define callbacks
callbacks = [
    EarlyStopping(patience=3, monitor='val_loss'),
]

# Training
encoder_input_data = X_train
decoder_input_data = y_train[:,:-1]
decoder_target_data = y_train[:,1:]

# Testing
encoder_input_test = X_test
decoder_input_test = y_test[:,:-1]
decoder_target_test= y_test[:,1:]

In [104]:
history = model5.fit([encoder_input_data, decoder_input_data],decoder_target_data,
                    epochs=EPOCHS,
                    batch_size=64,
                    validation_data = ([encoder_input_test, decoder_input_test],decoder_target_test ),
                    callbacks= callbacks)

Epoch 1/25
1125/1125 [==============================] - 156s 122ms/step - loss: 6.4053 - accuracy: 0.1596 - val_loss: 5.8604 - val_accuracy: 0.1966
Epoch 2/25
1125/1125 [==============================] - 131s 116ms/step - loss: 5.4863 - accuracy: 0.2171 - val_loss: 5.3919 - val_accuracy: 0.2341
Epoch 3/25
1125/1125 [==============================] - 132s 117ms/step - loss: 4.8652 - accuracy: 0.2532 - val_loss: 5.0411 - val_accuracy: 0.2587
Epoch 4/25
1125/1125 [==============================] - 132s 117ms/step - loss: 4.2996 - accuracy: 0.2893 - val_loss: 4.8257 - val_accuracy: 0.2794
Epoch 5/25
1125/1125 [==============================] - 132s 117ms/step - loss: 3.8215 - accuracy: 0.3274 - val_loss: 4.7003 - val_accuracy: 0.2980
Epoch 6/25
1125/1125 [==============================] - 131s 117ms/step - loss: 3.4151 - accuracy: 0.3677 - val_loss: 4.6375 - val_accuracy: 0.3110
Epoch 7/25
1125/1125 [==============================] - 132s 117ms/step - loss: 3.0696 - accuracy: 0.4120 - val_

In [118]:
weight = model5.get_weights()

In [119]:
weight

[array([[-2.27378849e-02,  2.21307017e-02, -3.23386118e-03, ...,
         -4.85489629e-02,  3.54363061e-02, -3.97939906e-02],
        [ 3.74090105e-01,  4.48100679e-02,  6.92501441e-02, ...,
         -9.60109606e-02, -1.40082553e-01,  1.11414485e-01],
        [ 4.58052397e-01,  2.90031862e-02,  3.12622190e-02, ...,
          1.16413787e-01, -1.73515275e-01,  2.26943232e-02],
        ...,
        [-1.27735525e-01, -3.86317857e-02, -1.10893212e-02, ...,
         -1.77227147e-02,  1.30627483e-01,  1.05597228e-01],
        [-3.52723524e-02, -4.57760558e-04, -2.14278139e-02, ...,
          2.55024191e-02,  1.79784551e-01,  4.58040088e-02],
        [ 2.25854665e-02, -1.96057290e-01, -2.63329800e-02, ...,
          7.63200447e-02,  6.24362379e-03, -3.86986621e-02]], dtype=float32),
 array([[-0.37167874, -0.73374665, -0.05106571, ..., -0.10903002,
         -0.260207  ,  0.23316036],
        [-0.00927074, -0.65154636, -0.13651069, ...,  0.24049193,
         -0.22701761,  0.52131957],
        [-

In [120]:
with open('model_weights_final.pkl', 'wb') as f:
    pickle.dump(weight, f)

In [121]:
with open('/content/drive/MyDrive/model_weights_final.pkl', 'wb') as f:
    pickle.dump(weight, f)

In [106]:
model5.save('model.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [107]:
model5.save_weights('model_weights.weights.h5')

In [117]:
weight

[array([[-2.27378849e-02,  2.21307017e-02, -3.23386118e-03, ...,
         -4.85489629e-02,  3.54363061e-02, -3.97939906e-02],
        [ 3.74090105e-01,  4.48100679e-02,  6.92501441e-02, ...,
         -9.60109606e-02, -1.40082553e-01,  1.11414485e-01],
        [ 4.58052397e-01,  2.90031862e-02,  3.12622190e-02, ...,
          1.16413787e-01, -1.73515275e-01,  2.26943232e-02],
        ...,
        [-1.27735525e-01, -3.86317857e-02, -1.10893212e-02, ...,
         -1.77227147e-02,  1.30627483e-01,  1.05597228e-01],
        [-3.52723524e-02, -4.57760558e-04, -2.14278139e-02, ...,
          2.55024191e-02,  1.79784551e-01,  4.58040088e-02],
        [ 2.25854665e-02, -1.96057290e-01, -2.63329800e-02, ...,
          7.63200447e-02,  6.24362379e-03, -3.86986621e-02]], dtype=float32),
 array([[-0.37167874, -0.73374665, -0.05106571, ..., -0.10903002,
         -0.260207  ,  0.23316036],
        [-0.00927074, -0.65154636, -0.13651069, ...,  0.24049193,
         -0.22701761,  0.52131957],
        [-

In [122]:
with open('/content/model_weights_final.pkl', 'rb') as f:
    data = pickle.load(f)

In [123]:
data

[array([[-2.27378849e-02,  2.21307017e-02, -3.23386118e-03, ...,
         -4.85489629e-02,  3.54363061e-02, -3.97939906e-02],
        [ 3.74090105e-01,  4.48100679e-02,  6.92501441e-02, ...,
         -9.60109606e-02, -1.40082553e-01,  1.11414485e-01],
        [ 4.58052397e-01,  2.90031862e-02,  3.12622190e-02, ...,
          1.16413787e-01, -1.73515275e-01,  2.26943232e-02],
        ...,
        [-1.27735525e-01, -3.86317857e-02, -1.10893212e-02, ...,
         -1.77227147e-02,  1.30627483e-01,  1.05597228e-01],
        [-3.52723524e-02, -4.57760558e-04, -2.14278139e-02, ...,
          2.55024191e-02,  1.79784551e-01,  4.58040088e-02],
        [ 2.25854665e-02, -1.96057290e-01, -2.63329800e-02, ...,
          7.63200447e-02,  6.24362379e-03, -3.86986621e-02]], dtype=float32),
 array([[-0.37167874, -0.73374665, -0.05106571, ..., -0.10903002,
         -0.260207  ,  0.23316036],
        [-0.00927074, -0.65154636, -0.13651069, ...,  0.24049193,
         -0.22701761,  0.52131957],
        [-

In [124]:
encoder_model = Model(encoder_input, encoder_states)
decoder_state_input_h = Input(shape=(512,))
decoder_state_input_c= Input(shape=(512,))
decoder_states_input= [decoder_state_input_h, decoder_state_input_c]

dec_embd2 = decoder_embd(decoder_input)

decoder_output2,state_h2, state_c2 = decoder_lstm(dec_embd2, initial_state=decoder_states_input)
deccoder_states2= [state_h2, state_c2]

decoder_output2 = decoder_dense(decoder_output2)

decoder_model = Model(
                      [decoder_input]+decoder_states_input,
                      [decoder_output2]+ deccoder_states2)

In [125]:


def get_predicted_sentence(input_seq):
    # Encode the input as state vectors.
    states_value = encoder_model.predict(input_seq)
    # Generate empty target sequence of length 1.
    target_seq = np.zeros((1,1))
    # Populate the first character of target sequence with the start character.
    target_seq[0, 0] = tokenizer_hindi.word_index['sos']

    # (to simplify, here we assume a batch of size 1).
    stop_condition = False
    decoded_sentence = ''

    while not stop_condition:
        output_tokens, h, c = decoder_model.predict([target_seq] + states_value)
        print(output_tokens[0,-1,:])
        # Sample a token
        sampled_token_index = np.argmax(output_tokens[0, -1, :])
        # print("output",sampled_token_index)
        if sampled_token_index==0:
          break
        else:
         # convert max index number to hindi word
         for key, value in tokenizer_hindi.word_index.items():
            if value == sampled_token_index:
                # print(f"The key for value 31723 is '{key}'")
                sampled_char=key
                break
        #  sampled_char = hindi_index[sampled_token_index]
        # aapend it to decoded sentence
        decoded_sentence += ' '+sampled_char

        # Exit condition: either hit max length or find stop token.
        if (sampled_char == 'eos' or len(decoded_sentence) >= 417):
            stop_condition = True

        # Update the target sequence (of length 1).
        target_seq = np.zeros((1,1))
        target_seq[0, 0] = sampled_token_index

        # Update states
        states_value = [h, c]

    return decoded_sentence

In [132]:
print("Hindi Sentence:",get_predicted_sentence(X_test[100].reshape(1,349))[:-4])

1/1 [==============================] - 0s 188ms/step
[1.5700458e-07 1.8487470e-09 1.3018899e-03 ... 2.4733462e-08 5.9473635e-09
 1.0421676e-08]
1/1 [==============================] - 0s 174ms/step
[3.0013214e-07 2.9852754e-09 1.5236708e-06 ... 2.3841004e-08 1.3931965e-10
 6.1285569e-12]
1/1 [==============================] - 0s 173ms/step
[1.2309859e-09 2.3219213e-11 1.4349795e-06 ... 1.3109582e-12 1.6462107e-13
 1.1914528e-12]
1/1 [==============================] - 0s 181ms/step
[9.3272178e-08 9.3752908e-09 8.4482936e-06 ... 1.8670693e-07 1.2107368e-09
 1.0613180e-09]
1/1 [==============================] - 0s 171ms/step
[1.04545414e-07 6.19510621e-09 5.26437689e-05 ... 1.59016009e-10
 3.13242099e-09 5.15061604e-10]
1/1 [==============================] - 0s 185ms/step
[1.3708530e-08 1.0131985e-09 6.1215621e-07 ... 1.9191004e-09 2.6471399e-12
 3.6011918e-12]
1/1 [==============================] - 0s 167ms/step
[6.9856833e-07 1.0039468e-08 2.9739042e-06 ... 4.4604580e-11 3.0505849e-09
 5

In [130]:
print("Hindi Sentence:",get_predicted_sentence(X_test[10].reshape(1,349))[:-4])

1/1 [==============================] - 0s 188ms/step
[2.3364461e-08 8.3822650e-11 7.7679819e-05 ... 8.2959898e-12 5.8710797e-12
 2.7836175e-10]
1/1 [==============================] - 0s 186ms/step
[4.3365515e-07 3.7464392e-09 1.3793734e-04 ... 6.6800544e-11 4.3011998e-09
 5.0171034e-10]
1/1 [==============================] - 0s 197ms/step
[3.3567584e-08 1.2291933e-08 2.8716084e-05 ... 6.8460202e-09 2.8919103e-10
 1.7530815e-11]
1/1 [==============================] - 0s 181ms/step
[9.6139065e-06 5.0245639e-09 8.2193446e-06 ... 3.7981124e-12 5.0688224e-13
 1.6510764e-09]
1/1 [==============================] - 0s 179ms/step
[1.6010374e-05 7.0904541e-08 5.9696317e-02 ... 2.1388466e-10 1.4155890e-07
 1.4869408e-09]
1/1 [==============================] - 0s 174ms/step
[4.6135074e-07 7.0864481e-10 1.4475068e-03 ... 5.0004475e-12 2.0688145e-13
 4.0898105e-12]
1/1 [==============================] - 0s 185ms/step
[7.4813624e-07 4.9577908e-10 1.1077108e-02 ... 5.9417613e-14 2.0243520e-11
 4.77473

In [134]:
print("Hindi Sentence:",get_predicted_sentence(X_test[1].reshape(1,349))[:-4])

1/1 [==============================] - 0s 187ms/step
[2.2824830e-07 2.5346640e-09 4.3542121e-04 ... 1.3320824e-08 3.7412780e-09
 3.8575312e-08]
1/1 [==============================] - 0s 197ms/step
[1.7606085e-07 4.2272958e-09 1.9141595e-05 ... 6.6997154e-09 3.2168001e-11
 1.2946279e-11]
1/1 [==============================] - 0s 182ms/step
[2.3666131e-09 1.4632795e-09 2.9420875e-08 ... 2.5788609e-09 2.4236195e-12
 7.8364686e-13]
1/1 [==============================] - 0s 167ms/step
[2.85576562e-07 1.36093945e-08 1.68466488e-06 ... 1.95655208e-08
 1.08086706e-12 6.48541576e-15]
1/1 [==============================] - 0s 182ms/step
[6.0842527e-09 7.1801978e-12 6.7768574e-06 ... 5.8819388e-13 8.8338747e-14
 2.5347472e-12]
1/1 [==============================] - 0s 161ms/step
[9.6200006e-07 1.7144607e-09 6.4070159e-06 ... 1.2611824e-09 7.8951272e-09
 8.1371195e-11]
1/1 [==============================] - 0s 177ms/step
[4.6690147e-08 4.2298600e-09 1.2518667e-07 ... 7.9126892e-09 1.0217095e-11
 2

In [136]:
wt = model5.get_weights()

In [137]:
wt

[array([[-2.27378849e-02,  2.21307017e-02, -3.23386118e-03, ...,
         -4.85489629e-02,  3.54363061e-02, -3.97939906e-02],
        [ 3.74090105e-01,  4.48100679e-02,  6.92501441e-02, ...,
         -9.60109606e-02, -1.40082553e-01,  1.11414485e-01],
        [ 4.58052397e-01,  2.90031862e-02,  3.12622190e-02, ...,
          1.16413787e-01, -1.73515275e-01,  2.26943232e-02],
        ...,
        [-1.27735525e-01, -3.86317857e-02, -1.10893212e-02, ...,
         -1.77227147e-02,  1.30627483e-01,  1.05597228e-01],
        [-3.52723524e-02, -4.57760558e-04, -2.14278139e-02, ...,
          2.55024191e-02,  1.79784551e-01,  4.58040088e-02],
        [ 2.25854665e-02, -1.96057290e-01, -2.63329800e-02, ...,
          7.63200447e-02,  6.24362379e-03, -3.86986621e-02]], dtype=float32),
 array([[-0.37167874, -0.73374665, -0.05106571, ..., -0.10903002,
         -0.260207  ,  0.23316036],
        [-0.00927074, -0.65154636, -0.13651069, ...,  0.24049193,
         -0.22701761,  0.52131957],
        [-

In [139]:
with open('/content/drive/MyDrive/model_weights_final2.pkl', 'wb') as f:
    pickle.dump(weight, f)

In [141]:
with open('model_weights_final2.pkl', 'wb') as f:
    pickle.dump(weight, f)